{
 "title": "Validator stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_version_info{validator_name!=\"\",validator_name!=\"Error: Usage information not found for the given command\"}",
     "legendFormat": "{{validator_name}} => {{version}}"
    }
   ]
  },
  {
   "title": "In Consensus Group",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "validator_inconsensus{validator_name!=\"\"}",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Penalty",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  validator_hbbft_perf{validator_name!=\"\", subtype=\"Penalty\"}",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Blockchain Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_height{validator_name!=\"\"}",
     "legendFormat": "{{validator_name}}"
    }
   ]
  }
 ]
}