{
 "title": "Helium Validator Dashboard",
 "tags": [
  "helium",
  "validators"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "validators",
    "label": "Validators",
    "query": {
     "query": "label_values(validator_version_info, validator_name) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Helium API stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oracle Price",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 3600,
       "fields": [
        { "jsonPath": "$.data.price", "type": "number" }
       ],
       "method": "GET",
       "urlPath": "/oracle/prices/current"
      }
     ]
    },
    {
     "title": "Block Height",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 60,
       "fields": [
        { "jsonPath": "$.data.block", "type": "number" }
       ],
       "method": "GET",
       "urlPath": "/oracle/prices/current"
      }
     ]
    },
    {
     "title": "Active Validators",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$.data.active", "type": "number" }
       ],
       "method": "GET",
       "urlPath": "/validators/stats"
      }
     ]
    },
    {
     "title": "Elected Validators",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$.data[*].address" },
        { "jsonPath": "$.data[*].name", "name": "" },
        { "jsonPath": "$.data[*].block_added", "name": "" }
       ],
       "method": "GET",
       "urlPath": "/validators/elected"
      }
     ]
    },
    {
     "title": "Avg Election Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        {
         "jsonPath": "$.data.election_times.last_day.avg"
        }
       ],
       "method": "GET",
       "urlPath": "/stats"
      }
     ]
    },
    {
     "title": "Avg Block Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        {
         "jsonPath": "$.data.block_times.last_day.avg"
        }
       ],
       "method": "GET",
       "urlPath": "/stats"
      }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"\"}) / sum(node_memory_MemTotal_bytes{cluster=\"\"})"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "validator_height", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "validator_version_info{validator_name!~\"^(Node|Error).*\"}"
    },
    {
     "expr": "sum(validator_height{validator_name!~\"^(Node|Error).*\"}) by (validator_name)",
     "legendFormat": "height"
    }
   ]
  },
  {
   "title": "HNT Rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(validator_api_balance) by (owner_address)) - 7154",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "USD Rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(validator_api_balance{}) by (owner_address)) - 7154",
     "legendFormat": "{{pod}}"
    },
    {
     "cacheDurationSeconds": 1800,
     "fields": [
      { "jsonPath": "$.data.price", "name": "", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/oracle/prices/current"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "validator_version_info", "legendFormat": "{{pod}}" }
   ]
  },
  { "title": "Validator stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Penalties & Consensus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(validator_ledger{subtype=\"total\"}) by (validator_name)",
     "legendFormat": "{{validator_name}}"
    },
    {
     "expr": "sum(validator_inconsensus) by (validator_name) ",
     "legendFormat": "in consensus ({{validator_name}})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"helium\",container=\"validator\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Block Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(validator_block_age) by (validator_name)",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(validator_height) by (validator_name)",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage (by validator)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"helium\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage (by node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (node)",
     "legendFormat": "{{node}}"
    },
    { "expr": "machine_cpu_cores", "legendFormat": "cores" }
   ]
  },
  {
   "title": "Memory Usage (by validator)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"helium\", container!=\"\", image!=\"\"}\n * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"helium\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (by node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{container!=\"\", image!=\"\"}\n * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (node)\n",
     "legendFormat": "{{node}}"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "memtotal" }
   ]
  },
  {
   "title": "Open file descriptors (by validator)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{namespace=\"helium\"}) by (pod)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Open file descriptors (by node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{node!~\"\"}) by (node)\n",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(node_procs_blocked{node!~\"\"}) by (node)\n"
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Disk Space (by validator)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"helium\"}))  by (persistentvolumeclaim))\n",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth (by validator)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"helium\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth (by node)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total[$__rate_interval])) by (node)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth (by validator)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"helium\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth (by node)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total[$__rate_interval])) by (node)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Penalty details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Penalty Details",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "sum(validator_ledger{subtype!=\"total\", validator_name=~\"$validators\"}) by (validator_name, subtype)",
       "legendFormat": "{{subtype}} ({{validator_name}})"
      }
     ]
    },
    {
     "title": "HBBFT Perf details",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sum(validator_hbbft_perf{validator_name=~\"$validators\"}) by (subtype, validator_name)",
       "legendFormat": "{{subtype}} ({{validator_name}})"
      }
     ]
    }
   ]
  }
 ]
}