#!/bin/bash

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update

STACK="kube-prometheus-stack"
CHART="prometheus-community/kube-prometheus-stack"
CHART_VERSION="12.7.0"
NAMESPACE="kube-prometheus-stack"

# use github hosted master version of values.yml
values="https://raw.githubusercontent.com/digitalocean/marketplace-kubernetes/master/stacks/kube-prometheus-stack/values.yml"

helm upgrade "$STACK" "$CHART" \
    --atomic \
    --create-namespace \
    --install \
    --namespace "$NAMESPACE" \
    --values "$values" \
    --version "$CHART_VERSION"
