#!/bin/bash

# upgrade DOKS 1-click monitoring stack (graf+prom+alertmanager)
# `kubernetes-monitoring-stack`
# https://marketplace.digitalocean.com/apps/kubernetes-monitoring-stack?iframe=true
#
# borrowed liberally from:
# https://github.com/digitalocean/marketplace-kubernetes/blob/master/stacks/kube-prometheus-stack/deploy.sh

set -e

cd "$(dirname "$0")"

source ../helper
source ../../.env

# Set default port
if [ -z "$GRAFANA_PORT" ]; then
  GRAFANA_PORT=3000
fi

kubectl port-forward svc/kube-prometheus-stack-grafana $GRAFANA_PORT:80 -n kube-prometheus-stack &
kubectl port-forward svc/kube-prometheus-stack-prometheus 9090 -n kube-prometheus-stack &
kubectl port-forward svc/kube-prometheus-stack-alertmanager 9093 -n kube-prometheus-stack &

echo "Visit =>"
echo -e "$(label 'Grafana' $GREEN): http://localhost:$GRAFANA_PORT -- user/pass=admin/prom-operator"
echo -e "$(label 'Prometheus' $GREEN): http://localhost:9090"
echo -e "$(label 'Alertmanager' $GREEN): http://localhost:9093"
echo
wait
echo "All done"
