#!/bin/bash
#
# forked from DigitalOcean's official marketplace app:
# wget "https://raw.githubusercontent.com/digitalocean/marketplace-kubernetes/master/stacks/kube-prometheus-stack/deploy.sh" -O install
#
# uses their values.yml configuration file as a default, but can be overloaded with values.yml file in this dir
# e.g. to fix macOS "path / is mounted on / but it is not a shared or slave" bug:
# https://github.com/prometheus-community/helm-charts/issues/467
#

set -e

CMD=$1

################################################################################
# chart
################################################################################
STACK="kube-prometheus-stack"
CHART="prometheus-community/kube-prometheus-stack"
CHART_VERSION="16.12.1"
NAMESPACE="kube-prometheus-stack"

cwd=$(dirname "$0")

k8s_folder=$(cd "$cwd"; cd ../../k8s/grafana; pwd)

if ! kubectl get namespaces --all-namespaces | grep -q $NAMESPACE; then
  echo "Creating $NAMESPACE namespace"
  kubectl create ns "$NAMESPACE"
fi

if [[ "$CMD" == "update-dashboard" ]] || [ -z "$CMD" ]; then
  echo "Adding Helium API data source"
  kubectl apply -n "$NAMESPACE" -f "$k8s_folder/helium-api-datasource.yml"
  echo "Adding Helium validator dashboard"
  kubectl apply -n "$NAMESPACE" -f "$k8s_folder/validator-dashboard.yml"
fi

if [ -z "$CMD" ]; then
  helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  helm repo update >/dev/null
  
  local_values="$cwd/values.yml"
  if [ -e "$local_values" ]; then
    echo "Using local values.yml file $local_values"
    values=$local_values
  else
    values="https://raw.githubusercontent.com/digitalocean/marketplace-kubernetes/master/stacks/kube-prometheus-stack/values.yml"
    echo "Using default DigitalOcean values.yml file $values"
  fi

  helm upgrade "$STACK" "$CHART" \
    --namespace "$NAMESPACE" \
    --values "$values" \
    --version "$CHART_VERSION" \
    --install \
    --atomic \
    --create-namespace

elif [[ "$CMD" == "uninstall" ]]; then

  kubectl delete -n "$NAMESPACE" -f "$k8s_folder/helium-api-datasource.yml"
  kubectl delete -n "$NAMESPACE" -f "$k8s_folder/validator-dashboard.yml"

  helm uninstall "$STACK" "$CHART" --namespace "$NAMESPACE"
fi
