apiVersion: v1
kind: Service
metadata:
  name: grafana-dns-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: subdomain.yourdomain.com
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana 
  ports:
    - protocol: TCP
      name: service
      port: 80
      targetPort: 3000