{
 "title": "Helium Validator Dashboard",
 "tags": [
  "helium",
  "validators"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "validators",
    "label": "Validators",
    "query": {
     "query": "label_values(validator_version_info, validator_name) "
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(validator_version_info{validator_name=~\"$validators\"}, pod) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Helium API stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oracle Price",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 3600,
       "fields": [
        { "jsonPath": "$.data.price", "type": "number" }
       ],
       "method": "GET",
       "urlPath": "/oracle/prices/current"
      }
     ]
    },
    {
     "title": "Block Height",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 60,
       "fields": [
        { "jsonPath": "$.data.block", "type": "number" }
       ],
       "method": "GET",
       "urlPath": "/oracle/prices/current"
      }
     ]
    },
    {
     "title": "Active Validators",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$.data.active", "type": "number" }
       ],
       "method": "GET",
       "urlPath": "/validators/stats"
      }
     ]
    },
    {
     "title": "Elected Validators",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$.data[*].address" },
        { "jsonPath": "$.data[*].name", "name": "" },
        { "jsonPath": "$.data[*].block_added", "name": "" }
       ],
       "method": "GET",
       "urlPath": "/validators/elected"
      }
     ]
    },
    {
     "title": "Avg Election Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        {
         "jsonPath": "$.data.election_times.last_day.avg"
        }
       ],
       "method": "GET",
       "urlPath": "/stats"
      }
     ]
    },
    {
     "title": "Avg Block Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        {
         "jsonPath": "$.data.block_times.last_day.avg"
        }
       ],
       "method": "GET",
       "urlPath": "/stats"
      }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"\"}) / sum(node_memory_MemTotal_bytes{cluster=\"\"})"
    }
   ]
  },
  {
   "title": "Earnings (HNT)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_api_rewards{validator_name=~\"$validators\"})  / 100000000",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "validator_version_info{validator_name=~\"$validators\"}"
    },
    {
     "expr": "sum(validator_height{validator_name=~\"$validators\"}) by (validator_name)",
     "legendFormat": "height"
    },
    {
     "expr": "sum(validator_api_rewards{validator_name=~\"$validators\"}) by (validator_name, validator_addr)",
     "legendFormat": "HNT"
    }
   ]
  },
  {
   "title": "Earnings (USD)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_api_rewards{validator_name=~\"$validators\"})  / 100000000",
     "legendFormat": "{{validator_name}}"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.data.price", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/oracle/prices/current"
    }
   ]
  },
  {
   "title": "Yield",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_api_rewards{validator_name=~\"$validators\"})  / 100000000 / (count(sum(validator_api_rewards{validator_name=~\"$validators\"}) by (validator_addr)) * 10000) * 100",
     "legendFormat": "Yield"
    }
   ]
  },
  { "title": "Validator stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Penalties & Consensus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(validator_ledger{subtype=\"total\"}) by (validator_name)",
     "legendFormat": "{{validator_name}}"
    },
    {
     "expr": "sum(validator_inconsensus) by (validator_name) * sum(validator_ledger{subtype=\"total\"}) by (validator_name)",
     "legendFormat": "in consensus ({{validator_name}})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"helium\",container=\"validator\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Block Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(validator_block_age{resource_type=\"BlockAge\"}) by (validator_name, pod)",
     "legendFormat": "{{validator_name}} ({{pod}})"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(validator_height) by (validator_name)",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "P2P Connections",
   "type": "timeseries",
   "description": "connections & sessions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(validator_connections{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P2P Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(validator_sessions{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Penalty Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Penalty Details",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(validator_ledger{subtype!=\"total\", validator_name=~\"$validators\"}) by (validator_name, subtype)",
       "legendFormat": "{{subtype}}/{{validator_name}}"
      },
      {
       "expr": "sum(validator_inconsensus{validator_name=~\"$validators\"}) by (validator_name) * max(validator_ledger{subtype!=\"total\", validator_name=~\"$validators\"}) by (validator_name)",
       "legendFormat": "in consensus {{validator_name}}"
      }
     ]
    },
    {
     "title": "HBBFT Perf details",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum(validator_hbbft_perf{validator_name=~\"$validators\",subtype!~\"Tenure|Penalty\"}) by (subtype, validator_name)",
       "legendFormat": "{{subtype}}/{{validator_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Hardware Resrouces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU Usage (by validator)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"helium\", pod=~\"$pod\"}) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage (by node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (node) / sum(machine_cpu_cores) by (node) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage (by validator)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"helium\", container!=\"\", image!=\"\", pod=~\"$pod\"}\n * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"helium\", pod=~\"$pod\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (by node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(\n    container_memory_working_set_bytes{container!=\"\", image!=\"\"}\n * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel\n) by (node))\n/\nsum(machine_memory_bytes) by (node)\n* 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Disk Space (by validator)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"helium\"}))  by (persistentvolumeclaim))\n",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Disk I/O (by validator)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{container=\"validator\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}/reads"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{container=\"validator\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}/writes"
      }
     ]
    },
    {
     "title": "Disk I/O (by node)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"$pod\"}[5m])) by (node)",
       "legendFormat": "{{node}}/reads"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$pod\"}[5m])) by (node)",
       "legendFormat": "{{node}}/writes"
      }
     ]
    },
    {
     "title": "Open file descriptors (by validator)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(process_open_fds{namespace=\"helium\",pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Open file descriptors (by node)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(process_open_fds{node!~\"\"}) by (node)\n",
       "legendFormat": "{{node}}"
      },
      {
       "expr": "sum(node_procs_blocked{node!~\"\"}) by (node)\n"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Receive Bandwidth (by validator)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"helium\",pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth (by node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth (by validator)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"helium\",pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth (by node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}