#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
cd $SCRIPT_DIR
source ../.env

CMD=$1
POD_NAME=validator

if [ -z $NAMESPACE ]; then
  echo "No namespace set. Defaulting to helium."
  NAMESPACE="helium"
fi

if [[ $CMD == "restart" ]]; then
  replica_id=$2

  if [ -z "$replica_id" ]; then
    # Delete all the validator pods. StatefulSet will automatically recreate them
    validator_count=$(kubectl get pods -n $NAMESPACE | grep -c "$POD_NAME")
    for ((i = 0 ; i < $validator_count ; i++)); do
      kubectl delete pod -n $NAMESPACE $POD_NAME-$i &
    done
  else
    # Just restart the pod specified
    kubectl delete pod $POD_NAME-$replica_id -n $NAMESPACE &
  fi
fi

kubectl apply -f ../k8s/validator.yml -n $NAMESPACE
kubectl apply -f ../k8s/exporter-service.yml -n $NAMESPACE