#!/bin/bash
POD_NAME=validator
CONTAINER_NAME=validator

function container_validator_version {
  replica=$1
  kubectl exec -it $POD_NAME-$replica -c $CONTAINER_NAME -n $NAMESPACE -- /bin/sh -c "miner versions" | egrep -o "[0-9]+.[0-9]+.[0-9]+" | xargs
}

function get_miner_name {
  replica=$1
  kubectl exec -it $POD_NAME-$replica -c $CONTAINER_NAME -n $NAMESPACE -- sh -c "miner info name" | egrep -o "[a-z]+-[a-z]+-[a-z]+" | xargs
}

function get_miner_address {
  replica=$1
  kubectl exec -it $POD_NAME-$replica -c $CONTAINER_NAME -n $NAMESPACE -- sh -c "miner peer addr" | grep -oE "[0-9a-zA-Z]{6,}"
}
