#!/bin/bash

validators=$(helium-wallet validators list | sed -e '1,3d' | sed '$d' | cut -b 3-54)

for val in $validators; do
  # echo -------- $val --------

  info=$(curl -s "https://testnet-api.helium.wtf/v1/validators/$val")
  name=$(echo $info | jq -r '.data .name')

  stats=$(curl -s "https://testnet-api.helium.wtf/v1/validators/$val/rewards/sum?min_time=-30%20day&bucket=day")
  # echo $stats | jq

  echo -n "$name,$val,"
  for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30; do 
    num=$(echo $stats | jq -r ".data[$i] .total")
    # echo -n "$i"
    # echo -n ","
    echo -n "$num"
    echo -n ","
  done
  echo

  sleep 1 # be nice to testnet API
done
