#!/bin/sh
# upgrade DOKS 1-click monitoring stack (graf+prom+alertmanager)
# `kubernetes-monitoring-stack`
# https://marketplace.digitalocean.com/apps/kubernetes-monitoring-stack?iframe=true
#
# borrowed liberally from:
# https://github.com/digitalocean/marketplace-kubernetes/blob/master/stacks/kube-prometheus-stack/deploy.sh


CMD=$1

if [ -z $CMD ]; then
  echo "$0: specify either 'install' or 'upgrade' command"
  exit 1
fi

if [[ $CMD == "upgrade" ]]; then
  helm repo update

  helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace kube-prometheus-stack
  helm upgrade metrics-server bitnami/metrics-server --namespace kube-system

  # check on things
  kubectl --namespace kube-prometheus-stack get pods -l "release=kube-prometheus-stack"

elif [[ $CMD == "install" ]]; then


  helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  helm repo update

  STACK="kube-prometheus-stack"
  CHART="prometheus-community/kube-prometheus-stack"
  CHART_VERSION="12.7.0"
  NAMESPACE="kube-prometheus-stack"

  # use github hosted master version of values.yml
  values="https://raw.githubusercontent.com/digitalocean/marketplace-kubernetes/master/stacks/kube-prometheus-stack/values.yml"

  helm upgrade "$STACK" "$CHART" \
    --atomic \
    --create-namespace \
    --install \
    --namespace "$NAMESPACE" \
    --values "$values" \
    --version "$CHART_VERSION"

else

  echo "Don't understand command $CMD"
  exit 1

fi
