#!/bin/bash

CMD=$1
KEY_NAME=swarm-keys

if [[ $CMD == "sync" ]]; then
  echo; echo "Downloading swarm_keys from cluster..."

  validator_count=$(kubectl get pods | grep -c "validator")
  for ((i = 0 ; i < $validator_count ; i++)); do
    pod="validator-$i"
    echo; echo "Pod: $pod"

    miner_name=$(kubectl exec -it $pod -c validator -- sh -c "miner info name" | egrep -o "[a-z]+-[a-z]+-[a-z]+" | xargs)
    address=$(kubectl exec -it $pod -c validator -- sh -c "miner peer addr")
    address=$(echo $address | sed 's/\/p2p\///')

    echo "Miner Name: $miner_name"
    echo "Miner Address: $address"

    mkdir -p keys
    mkdir -p keys/$miner_name

    kubectl cp $pod:/var/data/miner/swarm_key keys/$miner_name/swarm_key -c validator

    echo "Make sure you backup keys/$miner_name/swarm_key in 1password or place of choice."
  done

elif [[ $CMD == "swap" ]]; then
  replica_id=$2
  swarm_key_file_path=$3
  pod=validator-$replica_id

  echo; echo "Copying $swarm_key_file_path to $pod."
  kubectl cp $swarm_key_file_path $pod:/var/data/miner/swarm_key -c validator

  echo "Restarting $pod..."
  scripts/deploy restart $replica_id

else
  echo "$0: don't understand command '$CMD'"
  exit 1
fi
