#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
cd $SCRIPT_DIR

CMD=$1
QUAY_URL='https://quay.io/api/v1/repository/team-helium/validator/tag/?limit=20&page=1&onlyActiveTags=true'
ARCH=amd

source helper
source ../.env

if [[ $CMD == "update" ]]; then
  miner_quay=$(curl -s "$QUAY_URL" --write-out '\nHTTP_Response:%{http_code}')
  miner_response=$(echo "$miner_quay" | grep "HTTP_Response" | cut -d":" -f2)

  if [[ $miner_response -ne 200 ]]; then
    echo "Bad Response from Server"
    exit 0
  fi

  miner_latest_name=$(echo "$miner_quay" | grep -v HTTP_Response | jq -r -c --arg ARCH "$ARCH" '[ .tags[] | select( .name | contains($ARCH) and contains("latest-validator-")) ][0].name')
  miner_latest_sha=$(echo "$miner_quay" | grep -v HTTP_Response | jq -r -c --arg ARCH "$ARCH" '[ .tags[] | select( .name | contains($ARCH) and contains("latest-validator-")) ][0].manifest_digest')

  container_version=$(container_validator_version 0)
  container_version_sha=$(echo "$miner_quay" | grep -v HTTP_Response | jq -r -c --arg ARCH "$ARCH" --arg VER "$container_version" '[ .tags[] | select( .name | contains($ARCH) and contains($VER)) ][0].manifest_digest')

  # echo "$miner_latest_name: $miner_latest_sha"
  # echo "$container_version: $container_version_sha"

  if [ -z "$container_version" ]; then
    echo "Validator is not up right now. Try again later"
    exit 0
  fi

  if [[ $container_version_sha == $miner_latest_sha ]]; then
    echo "Already at latest version: $container_version"
  else
    echo "Out of date!"
    echo "Latest version: $miner_latest_sha"
    echo "Container version: $container_version_sha ($container_version)"
    ./deploy restart
  fi

elif [[ $CMD == "info" ]]; then
  replica_id=$2
  start_index=0
  validator_count=$(kubectl get pods | grep -c "validator")

  if [ ! -z $replica_id ]; then
    start_index=$replica_id
    validator_count=$((replica_id + 1))
  fi

  for ((i = $start_index; i < $validator_count; i++)); do
    pod="validator-$i"
    echo; echo -e "${GREEN}Pod:${NC} $pod"

    name=$(get_miner_name $i)
    address=$(get_miner_address $i)
    echo -e "${GREEN}Name:${NC} $name"
    echo -e "${GREEN}Address:${NC} $address"
    echo -e "${GREEN}Version:${NC} $(container_validator_version $i)"
    echo -e "${GREEN}Validator API:${NC} https://api.helium.io/v1/validators/$address"
    echo -e "${GREEN}Explorer:${NC} https://explorer-beta.helium.com/validators/$address"

    in_consensus="$(is_in_consensus $i)"
    if [[ $in_consensus =~ "true" ]]; then
      echo "Consensus group performance: "
      kubectl exec -it $pod -c validator -n $NAMESPACE -- sh -c "miner hbbft perf | grep $name"
    else
      echo "Not currently in consensus group"
    fi

    # echo "Quay: $QUAY_URL"
    kubectl exec -it $pod -c validator -n $NAMESPACE -- sh -c "miner info p2p_status"
  done

elif [[ $CMD == "peers" ]]; then
  # FIXME DRY up this "with each validator" loop
  validator_count=$(kubectl get pods | grep -c "validator")
  for ((i = 0; i < $validator_count; i++)); do
    pod="validator-$i"
    echo; echo "Pod: $pod"
    kubectl exec -it $pod -c validator -- sh -c "miner peer book -s"
  done

elif [[ $CMD == "cg_perf" ]]; then
  # pass additional arguments through, like "--format=csv"
  shift
  kubectl exec -it validator-0 -c validator -- sh -c "miner hbbft perf $@"

elif [[ $CMD == "bash" ]]; then
  pod_id=$2
  kubectl exec -it validator-$pod_id -c validator -- /bin/ash

elif [[ $CMD == "logs" ]]; then
  pod_id=$2
  kubectl exec validator-$pod_id -c validator -- tail -F /var/data/log/{console,error,crash}.log

elif [[ $CMD == "stake" ]]; then
  pod_id=$2
  wallet_path=$3
  amount=$4
  pod="validator-$i"

  if [ -z $pod_id ]; then
    echo "$0: missing pod_id (aka pod replica number)"
    exit 1
  elif [ -z $wallet_path ]; then
    echo "$0: missing path to wallet"
    exit 1
  elif [ -z $amount ]; then
    echo "No amount specified, assuming 10,000 HNT"
    amount=10000
  fi

  address=$(get_miner_address $pod_id)
  echo; echo "Name: $(get_miner_name $pod_id)"
  echo "Address: $address"
  echo "Wallet path: $wallet_path"
  echo "Stake amount: $amount"

  helium-wallet -f $wallet_path validators stake one $address $amount --commit

  echo; echo "Staked! Visit https://testnet-api.helium.wtf/v1/validators/$address to see the status"

elif [[ $CMD == "reset_db" ]]; then
  pod_id=$2

  if [ -z $pod_id ]; then
    echo "$0: missing pod_id (aka pod replica number)"
    exit 1
  fi

  kubectl exec -it validator-$pod_id -c validator -- sh -c "cd /var/data; rm -rf *.db; rm -rf blockchain_swarm; rm -rf log; rm -rf lost+found;"
  kubectl delete pod validator-$pod_id &

elif [[ $CMD == "kickstart" ]]; then
  pod_id=$2
  kubectl exec -it validator-$pod_id -c validator -- sh -c "miner peer connect /ip4/3.137.173.26/tcp/2154"

elif [[ $CMD == "top" ]]; then
  kubectl top pods --all-namespaces

else
  echo "$0: unknown command \"$CMD\" - (update|info|peers|cg_perf|bash|logs|stake|reset_db|kickstart)"
  exit 1
fi
